# Generated by Django 2.2.11 on 2020-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.FloatField(default=5.0, help_text="user's reputation based on the rides taken offerd"),
        ),
        migrations.AddField(
            model_name='profile',
            name='rides_offered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rides_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
