# Generated by Django 2.2.11 on 2020-05-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_raitings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raitings',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
