# Generated by Django 2.2.11 on 2020-04-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='verified',
            field=models.BooleanField(default=False, help_text='Public circles are listed in the main', verbose_name='verified circle'),
        ),
    ]
