# Generated by Django 2.2.11 on 2020-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_circle_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Public circles are listed in the main', verbose_name='public'),
        ),
    ]
