# Generated by Django 2.2.11 on 2020-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20200501_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of memebers', verbose_name='limited'),
        ),
        migrations.AddField(
            model_name='circle',
            name='memebers_limit',
            field=models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be limit on the number of memebers'),
        ),
    ]
