# Generated by Django 2.2.11 on 2020-05-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20200502_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remaining_invitation',
            new_name='remaining_invitations',
        ),
    ]
