# Generated by Django 2.2.11 on 2020-05-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_auto_20200502_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public circles are listed in the main', verbose_name='public'),
        ),
    ]
