# Generated by Django 2.2.11 on 2020-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_auto_20200505_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='memebers_limit',
            new_name='members_limit',
        ),
    ]
