# Generated by Django 2.2.11 on 2020-05-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0009_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='cirlce',
            new_name='circle',
        ),
    ]
